--- #YAML:1.0
name:                Log-Syslog-Abstract
version:             1.001
abstract:            Use any available syslog API
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Devel::Hide:                   0
    Test::Exception:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Dave O'Neill <dmo@roaringpenguin.com>
